# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import PyQt5.QtWidgets as qtwid
import serial
import sys



class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(482, 410)

        self.te_query = QtWidgets.QTextEdit(Dialog)
        self.te_query.setGeometry(QtCore.QRect(50, 330, 221, 51))
        self.te_query.setObjectName("lineEdit")

        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(25, 21, 421, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(20)

        for i in range (20):
            for value in range(1):
                self.tableWidget.setItem(i, value, qtwid.QTableWidgetItem(str(self.uart))) #표부분





        self.pushButton = QtWidgets.QPushButton(Dialog) #버튼부분
        self.pushButton.setGeometry(QtCore.QRect(330, 330, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.uart) #uart로 이동




    def uart(self):
        query = self.te_query.toPlainText()
        ser = serial.Serial("COM3", 115200, timeout=1)
        while True:
            op = query
            ser.write(op.encode())
            print("R:", ser.readline())
            return ser.readline()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
